### ISSUE TITLE
Internal error  An error occurred on the page you were trying to access. If you continue to experience problems please contact your Redmine administrator for assistance.  If you are the Redmine administrator, check your log files for details about the error.  Back

### ISSUE THREAD

**Issue by Bobotian** [akiko-pusu/redmine_issue_templates#159] opened 2017-08-15 09:48 UTC
hi,i met a mistake when i create a new project use redmine_issue_templates:
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

When i  see the log

have this mistake :

ActionView::Template::Error (uninitialized constant IssueTemplates::ProjectsHelperMethodsIssueTemplates::IssueTemplateSetting):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_issue_templates-0.1.6/lib/issue_templates/projects_helper_patch.rb:17:in `project_settings_tabs_with_issue_templates'
  plugins/redmine_work_time/lib/work_time_projects_helper_patch.rb:14:in `project_settings_tabs_with_work_time'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__515293623_87205836'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'

**Comment by akiko-pusu** [comment] 2017-08-15 10:07
Hi, @Bobotian 
Thanks for using my plugin.
Is this first time you use this plugin?

It seems you use version 0.1.6 of issue template, and stored as plugins/redmine_issue_templates-0.1.6.
(BTW, latest version is 0.1.8)

As I wrote in README, please note,  plugin's folder name should be "redmine_issue_templates". 
If changed, some migration task will be failed. 
Could you please confirm above?

If you still have trouble after confirming or renaming plugin’s directory, please let me know your environment, such as Redmine version, ruby version, other installed plugins.

**Comment by Bobotian** [comment] 2017-08-16 03:03
now i can see the templates,but when i click the "ISSUE模板列表/编辑ISSUE模板" also have the mistake：
‘Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back’

**Comment by akiko-pusu** [comment] 2017-08-16 03:07
Do you use non-asci character? I think this situation is related to #158.
Please confirm your database character setting.

**Comment by Bobotian** [comment] 2017-08-16 03:36
i need modify the database character setting?

**Comment by akiko-pusu** [comment] 2017-08-16 03:45
I can not say that completely. 

First, please check your Redmine’s logfile. Maybe more detailed informations are logged. 

Also, as I wrote above, please give me your environment information. 
Without these informations, I can hardly to support you, because I don’t know any information about your Redmine’s version, database you use, and so on.

> If you still have trouble after confirming or renaming plugin’s directory, please let me know your environment, such as Redmine version, ruby version, other installed plugins.

**Comment by Bobotian** [comment] 2017-08-16 11:47
About the  environment information,i use the Integrated software of redmine3.3 include duby.

this is the log
Processing by IssueTemplatesController#new as HTML
  Parameters: {"project_id"=>"branch32", "id"=>"branch32"}
  Current user: redmine (id=1)
  Rendered plugins/redmine_issue_templates/app/views/common/_nodata.html.erb (3.0ms)
  Rendered plugins/redmine_issue_templates/app/views/issue_templates/_form.html.erb (29.0ms)
  Rendered plugins/redmine_issue_templates/app/views/issue_templates/new.html.erb within layouts/base (53.0ms)
Completed 500 Internal Server Error in 214ms (ActiveRecord: 64.0ms)

ActionView::Template::Error (undefined local variable or method `checklist_json' for #<IssueTemplate:0xad25dc8>):
    39:                 onclick="addCheckList();">
    40:           </span>
    41:           <ul class='checklist' style='padding-left: 180px;'>
    42:             <% issue_template.checklist.each_with_index do |content, i| %>
    43:               <li id="checklist_<%= i %>">
    44:                 <span class="text">
    45:                   <%= content %>

**Comment by akiko-pusu** [comment] 2017-08-16 12:36
Ok, above information is enough.
Have you already been using this plugin before v0.1.2?
It seems you does not run migration task. There are some additional, rename, change column after v0.12, so please see README and run migration task.
(rake redmine:plugins:migrate RAILS_ENV=production  or bundle exec rake redmine:plugins:migrate RAILS_ENV=production)

**Comment by Bobotian** [comment] 2017-08-17 02:03
thanks ,do you know the different between linux and the windows system about the redmine_issue_templates.I want install the plugins on linux system

**Comment by akiko-pusu** [comment] 2017-08-17 02:39
Yes, of course, I can support Windows and Linux OS.

**Comment by Bobotian** [comment] 2017-08-17 02:41
that is to say,this plugins  can use on Linux OS?thanks

**Comment by akiko-pusu** [comment] 2017-08-17 02:48
Yes. Basically, not only this plugin but also other plugins can be use on Linux.

**Comment by Bobotian** [comment] 2017-08-21 12:47
hi,do you know the Checklist using methods, maybe you can give me some advice about the plugin,thanks

**Comment by akiko-pusu** [comment] 2017-08-21 14:26
Please see README and Install guide, https://www.r-labs.org/projects/issue-template/wiki/About_en#Plugin-installation 
That’s all.

I could not support you any more, without additional information about your environment.
Have you ever used Redmine? Or, is this the first time you use Redmine?

> Also, as I wrote above, please give me your environment information.
> Without these informations, I can hardly to support you, because I don’t know any information about > your Redmine’s version, database you use, and so on.

**Comment by wszychta** [comment] 2017-10-13 08:13
Hi,

I'm facing simillar problem.
My Enviroment is:

- Redmine issue template plugin 0.1.8 (upgraded from 0.0.9)
- Redmine version 3.4 (upgraded from 2.5.2)
- Ruby 2.4.0 from RVM
- Ruby Passanger 5.1.8
- HTTPD 2.2.15-60.el6.centos.5
- CentOS 6.9
- mysql-server 5.1.73-8.el6_8

I have done every steps to install new version of plugin (without errors) and I have enabled it for my all projects in administration settings. When I want to enter issues table I see internal error on page and error in my log file [redmine.log](https://github.com/akiko-pusu/redmine_issue_templates/files/1381822/redmine.log)

If you need any other informations just ask here.

**Comment by akiko-pusu** [comment] 2017-10-13 12:03
@wszychta 
Thanks for your report. I’ve reviewed your attached log, but I personally think this is not due to my plugin.
It seems this is caused by redmine_my_page_queries.

>   plugins/redmine_my_page_queries/lib/queries_helper_patch.rb:13:in `column_header_with_nilable_criteria’

Please try to remove (or stash)  redmine_my_page_queries plugin.

**Comment by wszychta** [comment] 2017-10-13 12:37
Please forgive me. You are right about that error. My problem was with other plugin. Thanks for your support.

**Comment by akiko-pusu** [comment] 2017-10-13 12:56
@wszychta No problem. 
And thanks for your prompt reply, and any informations are useful for me, for example, such as your environment information. 

If you don’t mind and have time, please let me know more about informations related to plugins, so I might help you.
You can get these informations from admin menu (infomation link), 
or run this command:
rake about (bundle exec rake about).

Various environment informations are useful not only for me but also every redmine users, because occasionally an error may occur with a combination of plugins.

**Comment by wszychta** [comment] 2017-10-13 13:04
@akiko-pusu 

Here you have output from bundle command. I wish It will help other people in future

Rails version              4.2.8
Ruby version              2.4.0-p0 (x86_64-linux)
RubyGems version          2.6.14
Rack version              1.6.8
Middleware                Rack::Sendfile, Rack::ContentLength, ActionDispatch::Static, Rack::Lock, #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x0000000321c750>, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::RemoteIp, ActionDispatch::Callbacks, ActiveRecord::ConnectionAdapters::ConnectionManagement, ActiveRecord::QueryCache, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ParamsParser, ActionDispatch::XmlParamsParser, Rack::Head, Rack::ConditionalGet, Rack::ETag, RequestStore::Middleware, OpenIdAuthentication
Application root          /opt/redmine-3.4
Environment               production
Database adapter          mysql2
Database schema version   20170419144536

**Comment by akiko-pusu** [comment] 2017-10-13 13:19
It’s so nice that using ruby 2.4.
BTW, could you please tell me what plugins you use? 
Sorry rake about command does not return the information about plugin....

You can get the information from Administration menu like this.
Plugin names and these version informations are important. 

<img width="902" alt="screen-shot" src="https://user-images.githubusercontent.com/122621/31548007-60ed11ca-b064-11e7-975a-7aa87edaeea7.png">

**Comment by wszychta** [comment] 2017-10-16 05:31
Environment:
  Redmine version                3.4.2.stable.16970
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_bootstrap_kit          0.1
  redmine_issue_templates        0.1.8
  redmine_spent_time             3.1.2

**Comment by akiko-pusu** [comment] 2017-10-16 06:36
@wszychta Thanks a lot!
Did you already remove redmine_my_page_queries? And has the problem solved?

**Comment by wszychta** [comment] 2017-10-17 05:22
Yes, as you can see in my last message. After removing this plugin everything started to work again.

**Comment by Bobotian** [comment] 2017-10-20 06:11
that's ok ,you can work now

**Comment by akiko-pusu** [comment] 2018-01-06 03:15
Hi, @Bobotian, @wszychta .
How have things been after that?
I close this issue, so please post new issue if you have any other trouble.

**Closed by akiko-pusu** 2018-01-06 03:15 UTC
Labels: question, wontfix

**Comment by vinesh1975** [comment] 2018-01-22 12:27
**Hi, @Bobotian, @wszychta .**

I am new to redmine. I installed redmine but I am getting this error when am clicking on the 
My Account, Creating new user "+ New User" link Edit link. 
I am unable to upload my screen shots to you due to error you tab just crashed: 

Please help!!!!


Bellow is message i am getting :

 http://192.168.1.108:8080/my/account

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back



Information

Redmine 3.2.1.stable

Default administrator account changed |                                                           -- ! --  RED
Attachments directory writable |                                                                        -- ! --   RED
Plugin assets directory writable (./public/plugin_assets) |                                 -- ! --  RED
RMagick available (optional) |                                                                             TICK  green                    
 ImageMagick convert available (optional) |                                                        TICK Green
                                         
Environment:
  Redmine version                 3.2.1.stable
  Ruby version                       2.3.6-p384 (2017-12-14) [x86_64-linux]
  Rails version                       4.2.5.2
  Environment                        production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                                  1.8.3.1
  Filesystem                     
Redmine plugins:
   no plugin installed

Kindly do the needful.....
Thank you for your help in advance.......
Regards
Vinesh M

**Comment by ankurjha21** [comment] 2018-01-23 10:36
To @vinesh1975 

Go through this it works for me 

https://mohitepramod.wordpress.com/2017/08/23/redmine-ticketing-tool-installation-on-ubuntu-14-0416-0/

**Comment by akiko-pusu** [comment] 2018-01-23 11:35
@vinesh1975 
I do hope to support you to solve above problem, but it seems your redmine is not installed any plugin.
Could you please give me more about information related to error, such as a part of production.log?

The error message you saw on browser is not enough.
You can find the log file named “production.log” under REDMINE_INSTALLED_DIRECTORY/logs .
Could you please send the last few lines, including some error / traceback messages?

> Internal error
> An error occurred on the page you were trying to access.
> If you continue to experience problems please contact your Redmine administrator for assistance.
> If you are the Redmine administrator, check your log files for details about the error.
> Back
> Information

Also, @ankurjha21 
Thanks so much for your support!
I’m not sure if vinesh1975 use Bitnami Redmine installer to install Redmine or not, but above is helpful for me.

**Comment by vinesh1975** [comment] 2018-02-03 11:18
Hi akiko-pusu, 

Kindly help me to setup redmine on centos 7 . Please provide me with configuration and installation step by step. I am in urgent need. Please help me. 



Thanks & Regards 


Vinesh Menon 

Mobile:+91 9072342819 
Phone: +91 4844000677 
Kruxsoft Solutions Pvt Ltd. 
Website: www.kruxsoft.com 





Confidentiality Notice: This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any distribution, copying or use of this communication or the information in it is strictly prohibited. If you have received this communication in error please notify us by e-mail info@kruxsoft.co.uk

**Comment by akiko-pusu** [comment] 2018-02-04 06:00
@vinesh1975 

Sorry the error you saw is not due to my plugin, so I can’t help you.
Also, this issue was already closed and please not to post any comment.

**Comment by vinesh1975** [comment] 2018-02-05 06:17
Hi akiko-pusu, 

The earlier mail you have send me was not my issue :) and that was not my error send to you from my end. 
below is my issue: 
Kindly help me to setup redmine on centos 7 . Please provide me with configuration and installation step by step. I am in urgent need. Please help me. 


Thanks & Regards 


Vinesh Menon 
Infrastructure Manager 
Mobile:+91 9072342819 
Phone: +91 4844000677 
Kruxsoft Solutions Pvt Ltd. 
Website: www.kruxsoft.com 





Confidentiality Notice: This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any distribution, copying or use of this communication or the information in it is strictly prohibited. If you have received this communication in error please notify us by e-mail info@kruxsoft.co.uk

**Comment by akiko-pusu** [comment] 2018-02-05 22:21
@vinesh1975

I’ve posted this reply from GitHub issue form.
Of course, I’m figure out your question is, but I could not support you.
Please close this  exchange and please don’t reply the email if you receive this message via email.

> below is my issue:
> Kindly help me to setup redmine on centos 7 . Please provide me with configuration and installation step by step. I am in urgent need. Please help me.
