### ISSUE TITLE
Rus lang

### ISSUE THREAD

**Issue by raspberry59** [akiko-pusu/redmine_issue_templates#74] opened 2017-01-11 04:06 UTC
The plugin does not work with the Russian language, when you save the template gives 500 error.

**Comment by akiko-pusu** [comment] 2017-01-30 18:14
Hi, @raspberry59 
Thank you so much for your posting issue.
But I’m sorry I could not reproduce this problem, with changing default and user preferred language into Russian. 

Could you please give me error informations, such as exception messages, logs?
I wonder this is related with database character-set, but I don’t know much about Russian language and its encoding.
Any additional information would be appreciated.

**Comment by akiko-pusu** [comment] 2017-03-06 07:04
@raspberry59 
How does your situation go?
Could you please let me know more information that I requested above?

I think one of the reason why 500 error happens is database or table encoding.
Please confirm database encoding with such as show variables like "chara%";  if you use MySQL.
Also please confirm table encoding with "show create table issue_templates:".

**Comment by akiko-pusu** [comment] 2017-08-21 14:35
Hi, @raspberry59 
Since there is no reply, I’m going to close this issue.

**Closed by akiko-pusu** 2017-08-21 14:35 UTC
Labels: wontfix
