### ISSUE TITLE
Cant install on Redmine 3.1.3

### ISSUE THREAD

**Issue by ciwebservice2** [akiko-pusu/redmine_issue_templates#180] opened 2018-04-12 13:19 UTC
Cant install last version

I see:

`rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /opt/bitnami/apps/redmine/htdocs-3-1-3)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating a_common_libs (A common libraries)...
Migrating redmine_agile (Redmine Agile plugin (Light version))...
Migrating redmine_auto_assign_user (Redmine Auto Assign User plugin)...
Migrating redmine_changeauthor (Redmine ChangeAuthor plugin)...
Migrating redmine_checklists (Redmine Checklists plugin (Light version))...
Migrating redmine_issue_templates (Redmine Issue Templates plugin)...
== 1 CreateIssueTemplates: migrating ==========================================
-- create_table(:issue_templates)
   -> 0.1579s
-- add_index(:issue_templates, :author_id)
   -> 0.3336s
-- add_index(:issue_templates, :project_id)
   -> 0.3337s
-- add_index(:issue_templates, :tracker_id)
   -> 0.2919s
== 1 CreateIssueTemplates: migrated (1.1206s) =================================

== 2 CreateIssueTemplateSettings: migrating ===================================
-- create_table(:issue_template_settings)
   -> 0.1569s
== 2 CreateIssueTemplateSettings: migrated (0.1580s) ==========================

== 3 AddIssueTitleToIssueTemplates: migrating =================================
-- add_column(:issue_templates, :issue_title, :string)
   -> 0.3907s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `acts_as_positioned' for #<Class:0x007f5c03cfe4d0>/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/opt/bitnami/apps/redmine/htdocs-3-1-3/plugins/redmine_issue_templates/app/models/concerns/issue_template/common.rb:19:in `block in <module:Common>'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/concern.rb:120:in `class_eval'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/concern.rb:120:in `append_features'
/opt/bitnami/apps/redmine/htdocs-3-1-3/plugins/redmine_issue_templates/app/models/issue_template.rb:3:in `include'
/opt/bitnami/apps/redmine/htdocs-3-1-3/plugins/redmine_issue_templates/app/models/issue_template.rb:3:in `<class:IssueTemplate>'
/opt/bitnami/apps/redmine/htdocs-3-1-3/plugins/redmine_issue_templates/app/models/issue_template.rb:1:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:360:in `require_or_load'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/apps/redmine/htdocs-3-1-3/plugins/redmine_issue_templates/db/migrate/0003_add_issue_title_to_issue_templates.rb:5:in `up'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in `up'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/opt/bitnami/ruby/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1046:in `ddl_transaction'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/opt/bitnami/apps/redmine/htdocs-3-1-3/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/bitnami/apps/redmine/htdocs-3-1-3/lib/redmine/plugin.rb:453:in `migrate'
/opt/bitnami/apps/redmine/htdocs-3-1-3/lib/redmine/plugin.rb:467:in `block in migrate'
/opt/bitnami/apps/redmine/htdocs-3-1-3/lib/redmine/plugin.rb:466:in `each'
/opt/bitnami/apps/redmine/htdocs-3-1-3/lib/redmine/plugin.rb:466:in `migrate'
/opt/bitnami/apps/redmine/htdocs-3-1-3/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
`

**Comment by OlivierP-VPG** [comment] 2018-05-17 12:48
Same issue with version 3.2.2 of Redmine. Please give us support ! :)

**Comment by jackdonovan** [comment] 2018-05-25 14:58
I am also having the same issue, my current Redmine version is 3.4.5. One of my other plugins migrates successfully, but this one causes the rake to abort with the same output as @ciwebservice2 .

**Comment by jackdonovan** [comment] 2018-05-25 17:56
Update - I figured out my problem, posting just in case it fixes any of yours. Still on Redmine 3.4.5.stable, I did the rake command with sudo because I assumed there was a permissions problem (Maybe this is the problem @ciwebservice2 and @OlivierP-VPG  may have?) then I made sure to check the redmine_issue_templates file permissions and user/group. They were root at this point, and on my config they must be switched when working with bitnami (@ciwebservice2  you seem to also be working with bitnami based on your file paths). The two folders you need to check permissions are in htdocs/plugins and htdocs/public/plugin_assets. just make sure that the permissions are set up correctly according to your configuration in bitnami, and you should be good to go once you restart redmine. My issue was resolved by this.

**Comment by akiko-pusu** [comment] 2018-05-25 23:46
Hi, @ciwebservice2 @OlivierP-VPG 
Thank you so much for your reporting this issue, and I’m deeply sorry to trouble you.
Since version 0.1.9,  Issue Template supports drag and drop reordering  template list with using the feature Redmine itself implemented. 
But, unfortunaltelly, this Redmine’s feature had released from version 3.3.
(Ref: http://www.redmine.org/issues/12909)

So, if you use Redmine version 3.2.x or before, my latest plugin will be failed to install.
I am sorry for my carelessness and for any inconvenience. 

If you hope to use my template plugin without version up your Redmine, please use the Template plugin version **0.1.8**.

You can download from here:   https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/0.1.8 
Or clone and checkout the branch tagged as 0.1.8.

Soon I will change the init.rb against the latest master branch, to  prevent install against Redmine 3.3 or before.

Please feel free to report if you try to re-install with version 0.1.8.
I’ll do my best to support you.

**Comment by akiko-pusu** [comment] 2018-05-26 01:41
@jackdonovan 
Thank you so much for your trying my plugin and giving valuable information.
Above was quite helpful for me to find what is the main cause of this issue. 

As I wrote above, latest version of this plugin works against Redmine 3.4.x only. 
So I’m also going to support your situation.
Please let me know if You still have some problems.

**Comment by akiko-pusu** [comment] 2018-05-26 12:35
@ciwebservice2 
Now I’m trying to release bug fix version which supports from Redmine 3.1 to Redmine 3.4.
Please wait for a while.

**Comment by akiko-pusu** [comment] 2018-05-28 01:46
@ciwebservice2 @OlivierP-VPG @jackdonovan 
Sorry to cause you inconvenience. I've released v0.2.0 as bugfix version.
If you had a time to update, please try the latest (master) version.

**Comment by OlivierP-VPG** [comment] 2018-05-28 09:43
@ciwebservice2 works like a charm, thanks a lot for your support!

**Comment by akiko-pusu** [comment] 2018-05-28 10:50
@OlivierP-VPG I’m glad to hear that!
The Information that this plugin works on various environments is quite useful for me,  also for someone who is going to try this plugin.

**Comment by jackdonovan** [comment] 2018-05-29 14:21
@akiko-pusu  Version 0.2.0 worked flawlessly as intended on Redmine version 3.4.5.stable! Migration completed easily and had no problems. Thank you for your support and urgency during this issue.

**Closed** 2018-09-01 23:01 UTC

**Comment by akiko-pusu** [comment] 2018-09-01 23:05
Thanks for reporting this issue and many comments, so I was able to correct the problem.
