### ISSUE TITLE
Template body not loaded into issue answer (v.1.0.3 only)

### ISSUE THREAD

**Issue by ChrisUHZ** [akiko-pusu/redmine_issue_templates#356] opened 2020-06-29 06:57 UTC
## Description
The Template body is no longer loaded into the issue answer with the Version 1.0.3. It works like a charm in version 1.0.2.
Happens only with editing issues - creating new issues, template loading works perfect!

## Environment
Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.17
  redmine_ckeditor               1.2.3
  redmine_contacts               4.3.0
  redmine_contacts_helpdesk      4.1.8
  redmine_issue_badge            0.1.3
  redmine_issue_templates        1.0.2
  redmine_lightbox2              0.5.1
  redmine_questions              1.0.2

## Visual Proof / Screenshot
![grafik](https://user-images.githubusercontent.com/57802892/85982582-6537e500-b9e6-11ea-9c60-fa4982531ff3.png)
![grafik](https://user-images.githubusercontent.com/57802892/85982800-b942c980-b9e6-11ea-8b67-2a697d062438.png)

## Expected Results
Loading template body in editing issues answer

## Actual Results
Not loading template body in editing issues answer

## Workaround
roll back to version 1.0.2

**Comment by akiko-pusu** [comment] 2020-06-29 12:59
Hi, @ChrisUHZ, thanks for your reporting!

**Comment by akiko-pusu** [comment] 2020-06-29 13:40
@ChrisUHZ Could you give the error messages if your browser has some JavaScript error message?
And it seems this is due to a combination with CKEditor.

**Comment by ChrisUHZ** [comment] 2020-06-30 07:00
@akiko-pusu I´m sorry but there are **no** error messages. Neither Javascript, nor in the logs of the webserver (apache/production).
I removed ckeditor and some more plugins, but still i have the same problem as described before :(

Redmine plugins:
  redmine_contacts                   4.3.0
  redmine_contacts_helpdesk    4.1.8
  redmine_issue_templates        1.0.3

**Comment by akiko-pusu** [comment] 2020-06-30 23:30
I'm glad if you tell me what browser you use.

**Comment by akiko-pusu** [comment] 2020-07-02 01:13
@ChrisUHZ 
Ok, thanks for your time and many responses!
Let me confirm the situation.

- With version 1.0.3, the template is applied correctly **when "creating new issue".**  Is that right?
- With version 1.0.3,  the **template for note** is not applied to the note (journal) textarea. Is that right?

As you know, now template plugin has 2 kind of featue.
1 is template for Issue Description.
2 is template for Note (Journal).

Above capture, it seems you describe about "Notizvorlage" (template for note).

**Comment by ChrisUHZ** [comment] 2020-07-02 07:18
@akiko-pusu: I tested Firefox 64bit, 77.0.1 and Chrome 32bint, 83.0.4103.106
And yes, v. 1.0.3 creating a **new** issue the template is applied correctly, appling templates in **editing** issues (note/journal) textarea ("answers" to the costumer) is not working.
Correct: in my case, it is the "Notizvorlage" => note template.

**Comment by akiko-pusu** [comment] 2020-07-02 15:59
Thanks again!
It's difficult for me to figure out the reason.
If you have time and interest, try to debug the JavaScript function is called or not.

When you click the right side of the arrow, the JavaScript function named "applyNoteTemplate" should be called and the request to the server-side is sent.

### 1. add the source map setting

Please add the line ``//# sourceURL=note-template.js`` inside the  **app/views/issue_templates/_note_form.html.erb** like this.

```diff

diff --git a/app/views/issue_templates/_note_form.html.erb b/app/views/issue_templates/_note_form.html.erb
index 42015e4..fb26d30 100644
--- a/app/views/issue_templates/_note_form.html.erb
+++ b/app/views/issue_templates/_note_form.html.erb
@@ -122,4 +122,6 @@ function applyNoteTemplate(event, template_id) {
   req.setRequestHeader('Content-Type', 'application/json')
   req.send(JSON.stringify(JSONdata))
 }
+
+//# sourceURL=note-template.js
 </script>
```

### 2. Go to issue edit page and open Chrome Developer tool

You can see the JavaScript file named "note-template.js" at the source tab.
Then, add the breakpoint at ``function applyNoteTemplate(event, template_id) ....``

If you click the arrow to apply a template, the click event is fired and applyNoteTemplate() function is called.
If there is something error, applyNoteTemplate()  will be never called.

<img width="750" alt="debug-note-template" src="https://user-images.githubusercontent.com/122621/86381099-e2ee4000-bcc7-11ea-8081-5bb37a274525.png">

Could you please send or send the screenshot if some error message is displayed at JavaScript console.



Here is a short movie for debugging. I hope this would be any help.
https://www.youtube.com/watch?v=746-I07C9TY

**Comment by ChrisUHZ** [comment] 2020-07-03 09:03
@akiko-pusu
I added the line **//# sourceURL=note-template.js** into the file **app/views/issue_templates/_note_form.html.erb** like this:
![grafik](https://user-images.githubusercontent.com/57802892/86450829-69337200-bd1a-11ea-8a8e-a34a595b590d.png)

Following your instructions, i opend redmine in chrome, switched to debbuging and tried to follow your instructions within the video. But first i mentioned some differenc between your _note_form_html.erb file:
![grafik](https://user-images.githubusercontent.com/57802892/86451086-b0216780-bd1a-11ea-8b5b-65a03eede0d8.png)
Mine looks different then yours??

I continued debbuging, loaded the page, switched to answer, loaded the template dialog and then this error popped up:
![grafik](https://user-images.githubusercontent.com/57802892/86451313-055d7900-bd1b-11ea-856b-f6dcb025dae1.png)

I searched for the function and for me, it seemed to be loaded "normal":
![grafik](https://user-images.githubusercontent.com/57802892/86451501-4b1a4180-bd1b-11ea-914e-a27dfdece3cf.png)
![grafik](https://user-images.githubusercontent.com/57802892/86451552-5c634e00-bd1b-11ea-9a8d-76379e07acee.png)

**Comment by akiko-pusu** [comment] 2020-07-03 12:18
Oh, sorry for my poor instruction.
Your pointing out is right and greatly helpful!!!
It's my bug.

I've just committed a single change to this bug.
Could you please try  e042e41. It might be effective!

Thanks to you, I've confirmed that v1.0.3 (supporting jQuery 3.x) works fine. (except my bug....)

**Comment by akiko-pusu** [comment] 2020-07-05 14:49
Fixed: #359

**Closed by akiko-pusu** 2020-07-05 14:49 UTC
Labels: bug

**Comment by ChrisUHZ** [comment] 2020-07-08 13:22
@akiko-pusu It works like a charm! Thank you again for fixing this bug so fast - i really appreciate!

**Comment by akiko-pusu** [comment] 2020-07-09 03:37
Your welcome!
Thanks for pair debugging and valuable information!
