### ISSUE TITLE
Sometimes, Task template is not shown.

### ISSUE THREAD

**Issue by luckygg** [akiko-pusu/redmine_issue_templates#193] opened 2018-08-09 08:37 UTC
## Summary
Sometimes, Task template is not shown.

## Description
When I create a new task, the template is shown or not.
If it is not shown I do as below :
① Click the clear button.
② Click the 'Preview Template Contents' button.
③ Select the template and apply.

## Environment
- Redmine version
3.3.6.stable

- Installed plugins
clipboard_image_paste          1.12
  progressive_projects_list      3.0.1
  redmine_ckeditor               1.1.5
  redmine_custom_reports         0.1.5
  redmine_dmsf                   1.6.0
  redmine_highlightjs            1.0.3
  redmine_issue_checklist        2.1.0
  redmine_issue_templates        0.1.9
  redmine_lightbox2              0.3.5
  redmine_local_avatars          1.0.3
  redmine_monitoring_controlling 0.1.1
  redmine_startpage              0.1.0

- Ruby version
2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]

- OS Platform
Synology NAS 

- Database (MariaDB, MySQL, PostgreSQL) and its version
MariaDB 10.0.34

- Rails Env
4.2.7.1

**Comment by pbatroff** [comment] 2018-10-16 08:44
I have the same Problem. Template is loading when the initial template is applied, but changes to the tracker aren't properly applied, or sometimes added (e.g. in subject). 

The issue Body isn't upgraded at all, the only way I could force a reload was to delete subject and description, then chose templates and in the pop-up manually choose the body etc ... 

I tracked this down to an incompatibility with ckEditor. It seems It messes a bit with the pre filled templates.

I have Version 1.1.5 of CKEditor installed, with 0.2 of redmine_issue_template.

**Comment by akiko-pusu** [comment] 2018-10-17 15:47
Hi, @pbatroff. 
Thanks for your additional information, and it’s quite helpful for me....

> I tracked this down to an incompatibility with ckEditor. 

I’ll confirm if I can reproduce this problem with using CKEditor.

**Comment by akiko-pusu** [comment] 2018-10-29 02:51
I could confirm the situation, and sorry for my delayed reply.
It seems this is because this issue template try to apply its template text to CKE editor before CKE Editor's text area is rendered. 
When tracker is changed, first, CKE editor is rendered only the buttons or toolbar. Then, text area (input form) is displayed with using iframe.
Maybe I could make some workaround with catching then event that CKE Editor's textarea become activated.

**Comment by akiko-pusu** [comment] 2018-11-01 00:30
BTW:
> It seems this is because this issue template try to apply its template text to CKE editor before CKE Editor's text area is rendered.
So, I think this is not a my bug and it’s difficult for me to understand another plugin’s behavior.
Sorry to delayed reply and action 🙏

**Comment by pbatroff** [comment] 2018-11-05 09:13
Hey, 

thanks for the patch and quick update! I installed the current master version (0.2.1?), since the branch got merged I think. 

I have good news and bad news: Good news is, that templates text is now injected properly, but once there is already text in the issue, template code is appended, in topic as well as in the issue body. I'm not sure if that works as intended, but I thought this is worth the mention!  

Overall I think this is much more reliable now, thanks for the update!

**Comment by akiko-pusu** [comment] 2018-11-05 09:53
@pbatroff 
Thanks for your feedback and report!

That's too bad...

> but once there is already text in the issue, template code is appended, in topic as well as in the issue body.

Let me confirm, do you set "Replace subject and description" option at project settings tab?

![Replace subject and description option](https://www.redmine.org/attachments/download/11445/template-option.png)

And if you don't mind, please upload some captures.

**Comment by pbatroff** [comment] 2018-11-05 09:56
Ahh, I feel stupid now! It wasn't checked, and it now fully works as intended! Thanks for the hint!

**Comment by akiko-pusu** [comment] 2018-11-05 10:29
I was relieved to hear that.
But I'm not sure this workaround is effective in all cases, so let's keep an eye on things for a while. 
Feel free to comment if there is something strange 😃

**Closed** 2018-11-11 12:44 UTC
Labels: bug, wait to confirm
