### ISSUE TITLE
can't display issue_template when i create a new issue

### ISSUE THREAD

**Issue by hexistore** [akiko-pusu/redmine_issue_templates#140] opened 2017-07-06 06:59 UTC
Uncaught ReferenceError: ISSUE_TEMPLATE is not defined
    at HTMLDocument.<anonymous> (new:239)
    at j (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at Function.ready (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at HTMLDocument.J (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)

**Comment by akiko-pusu** [comment] 2017-07-06 09:05
Hi, @hexistore. Thanks for using my plugin.
I’d like to support you but could you please give me some more informations?
Above information is too short for me to support your issue.

If you could, please let me know following informations:

Redmine version / ruby version / Issue Template plugin’s version, any other plugin if you use.
You can get above from http://your_redmine_url/admin/info screen.

Also production log is helpful for me.

**Comment by peternijssen** [comment] 2017-07-26 09:15
Same issue over here.

```
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
```

Nothing in the logs, just the console:

```
Uncaught ReferenceError: ISSUE_TEMPLATE is not defined
    at HTMLDocument.<anonymous> (new:275)
    at j (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at Function.ready (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at HTMLDocument.J (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
```

Piece of code it seems to be referring to:
https://github.com/akiko-pusu/redmine_issue_templates/blob/aef6f9fa9574acc49f3bdc7afe4dc364002d2c57/app/views/issue_templates/_issue_select_form.html.erb#L56

**Comment by peternijssen** [comment] 2017-07-26 09:52
And the issue is solved by doing a browser cache clear / disabling cache.

**Comment by akiko-pusu** [comment] 2017-07-26 11:00
@peternijssen 
Thanks for using my plugin and issue reporting.
It seems this problem is related to Redmine’s issue: http://www.redmine.org/issues/24617
This issue was fixed at recently release, Redmine 3.4 and later.
So, please super-reload your browser or clear cache after update plugin not only mine but also any other plugins.

Of course if there are some other problems related my plugin, feel free to report.

**Comment by akiko-pusu** [comment] 2017-08-21 14:32
Hi, @hexistore 
How does your situation goes?

**Comment by akiko-pusu** [comment] 2018-01-06 03:17
I close this issue, so please post new issue if you have any other trouble.
Thank you for your reporting issue!

**Closed by akiko-pusu** 2018-01-06 03:17 UTC
Labels: wontfix
