### ISSUE TITLE
Global templates can not be associated with each project from project settings tab

### ISSUE THREAD

**Issue by jozzlee** [akiko-pusu/redmine_issue_templates#157] opened 2017-08-11 09:44 UTC
I want to create a global template and allow the user (not admin) to use it in all projects，but i cann't.

[Known restrictions](https://www.r-labs.org/projects/issue-template/wiki/About_en#Known-issue)
Global templates can not be associated with each project from project settings tab. (Now only Administrator do this work)
Global template is not defined as a default template.

**Comment by akiko-pusu** [comment] 2017-08-12 14:10
Hi, jozzlee. Thanks for your reporting.

> Global templates can not be associated with each project from project settings tab. (Now only  Administrator do this work)

Yes, the user can create and maintain global templates is only Administrator. 
And only administrator can associated the template to projects.

I personally this is enough feature. 
Could you please tell me more details about this request, you situation? 


> Global template is not defined as a default template.

Please see README.md and Redline’s plugin information.
(http://www.redmine.org/plugins/redmine_issue_templates)

From version 0.1.5, global issue template can be defined as “default” of target tracker.
(This setting is overwrited by project’s default template.)

**Comment by jozzlee** [comment] 2017-08-15 03:46
Hi, akiko-pusu.
The feature is not enough for multi project. When you create a project, you frequently need to repeat actions. It's not efficient.

**Comment by akiko-pusu** [comment] 2017-08-15 04:36
How about inherit template?

**Comment by jozzlee** [comment] 2017-08-15 06:08
it is no work. "apply global template to all projects” still only administrator can use the template to create new issue.
> "apply global template to all projects” is activated, global templates are applied to all projects and confidential content will be exposed to all the user who can create new issue.

> Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.4
  redmine_checklists             3.1.6
  redmine_issue_templates        0.1.8
  redmine_work_time              0.3.4

**Comment by akiko-pusu** [comment] 2017-08-15 08:48
Do you set role correctly?

**Comment by jozzlee** [comment] 2017-08-16 00:22
Configured correctly, but no work.
I try set all permissions for user, still no work.

**Comment by akiko-pusu** [comment] 2017-08-16 02:16
Here are sample screen shots.
E.g. User “hope” is assigned to Developer role on some project.
Developer role has a permission of “Show templates”.

--------

<img width="400" alt="permission" src="https://user-images.githubusercontent.com/122621/29344438-d105afaa-8272-11e7-966c-9bbfb10b0384.png">

If this user access list template screen of his project, not only project local templates but also global issue templates are shown. (In case global issue templates are associated with target project or activated global templates site widely.) 

<img width="450" alt="list-template-screen" src="https://user-images.githubusercontent.com/122621/29344457-eaf4d17a-8272-11e7-8842-51a777bba5b0.png">

When user open a new issue screen, pulldown for selecting templates are shown, including global issue templates.
Not only this, but also use can preview template contents by clicking “Preview template contents” link.

<img width="450" alt="preview-templates" src="https://user-images.githubusercontent.com/122621/29344462-f388526c-8272-11e7-90d1-52d1d3df586c.png”>

Of course, not only global templates but also project local templates should be marked as “Enabled” to use.

The all I’ve implemented.
Are there any differences from the features you are imagining?

**Comment by jozzlee** [comment] 2017-08-17 07:14
screen 1,2,4 set done. but screen 3, when user open a new issue screen, pulldown for selecting templates are **NOT** shown

**Comment by akiko-pusu** [comment] 2017-08-17 08:49
What version of your Redmine?
**More informations are required to support you.**

Could you copy and paste the informations of your Redmine. You can get these information on Administrator screen, such as information menu.

**Comment by akiko-pusu** [comment] 2017-08-17 09:08
Also please confirm your log, if there are Some error messages or not. 
If there is no information, this situation is out of my hands.

**Comment by jozzlee** [comment] 2017-08-18 00:20
I try clear Browser cache and server cache,still not work again. Now i will try upgrade redmine to 3.4. Anyway, I'll report it again.
`bundle exec rake tmp:cache:clear tmp:sessions:clear RAILS_ENV=production`

**Comment by akiko-pusu** [comment] 2017-08-18 00:28
Ok, please follow plugin's README. 
In any case, I need production log to figure out the problem. (Do you know haw to see the production log?)
In addition to this, browser's developer tool would be helpful to debug. Please check traffic status to server-side, ajax requests, and JavaScript message.

**Comment by jozzlee** [comment] 2017-08-18 02:48
The problem was found.

**Comment by akiko-pusu** [comment] 2017-08-18 03:04
@jozzlee Thanks for your reply and information.
I'm sorry I don't know the browser that you say, 360 browser.... Only IE, Firefox, Chrome Safari are supported.
May the problem is related to jQuery?

**Comment by akiko-pusu** [comment] 2017-08-21 14:29
Since there is no reply, I’m going to close this issue.
Please open new issue if you have any other problem.

**Closed by akiko-pusu** 2017-08-21 14:29 UTC
Labels: question, wontfix
