### ISSUE TITLE
Template duplicates when changing Status or Category fields

### ISSUE THREAD

**Issue by mark-hrh** [akiko-pusu/redmine_issue_templates#354] opened 2020-06-24 11:09 UTC
## Summary
Updating the Status field after filling in a template description details causes the template to be appended again. 

## Description
1) Create a new issue that has a template
   - Template set as default
  - Template setting 'Replace subject and description' is *not* checked

![IssueTemplateSettings](https://user-images.githubusercontent.com/61697646/85542398-f5ee7980-b610-11ea-8ce5-de7296a0858c.png)

2) Partially fill the template
3) Change the 'Status' or 'Category' fields on the issue

## Environment

Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Mercurial                      3.7.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  collab                         1.1
  redmine_agile                  1.5.3
  redmine_issue_templates        1.0.2

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.

![TemplatesIssue](https://user-images.githubusercontent.com/61697646/85544668-21726380-b613-11ea-9dee-470affb9622d.gif)

## Expected Results
The description does not change

## Actual Results
The description updates so the template is appended again.

## Workaround

Please let me know if you have any workaround.

**Comment by akiko-pusu** [comment] 2020-06-25 23:03
Hi, @mark-hrh 
Thank you so much for your detailed issue reporting.
Since reports about the latest version 1.x  are not so many, this issue is so valuable for me.
I really appreciate it. 

Please wait for a while to reproduce and fix the problem.

**Comment by akiko-pusu** [comment] 2020-06-29 15:00
Hi, @mark-hrh

This is not a bug.
The HTTP request runs when update issue status or tracker. **This is due to Redmine's default behavior.**

And please confirm that you edit the issue description just after the loaded default template.
(You append the text "abc")

So, JavaScript of Issue Templates judges the issue description text is changed.
In this case, JavaScript of Issue Templates keeps the description of issue and appends after the description.

**Comment by akiko-pusu** [comment] 2020-06-30 02:13
@mark-hrh 
Thanks for the above repor.
I've just released IssueTemplate 1.0.3. This latest version, I rewrote JavaSctipt code significantly.
So I'm afraid template does not work fine in your env.

I'm going to create a workaround as a patch and provide you.
If you don't mind, I hope you try and evaluate the patch, to confirm it's effective.
Please wait for a while.

**Comment by akiko-pusu** [comment] 2020-06-30 23:32
## Workaround: 1

If you use version 1.0.3, please try this:
https://github.com/akiko-pusu/redmine_issue_templates/pull/358/files

(I'm going to merge into my master branch)

**Comment by akiko-pusu** [comment] 2020-07-05 14:47
Fixed on #358

**Closed by akiko-pusu** 2020-07-05 14:47 UTC
Labels: refactor, wait to confirm

**Comment by mark-hrh** [comment] 2020-07-14 07:14
Hi @akiko-pusu . Sorry for not replying, I was on holiday. I have installed version 1.0.4 and can confirm this fixes my issue. Thank you very much :-)

**Comment by akiko-pusu** [comment] 2020-07-14 13:46
Thanks! I'm relieved to hear that!
