### ISSUE TITLE
Description layout issue when use with minimalflat2 template

### ISSUE THREAD

**Issue by LeGiangAnh** [akiko-pusu/redmine_issue_templates#51] opened 2016-08-08 04:23 UTC
Hi,

I'm using your plugin with [Miniflat2 theme](https://github.com/akabekobeko/redmine-theme-minimalflat2). I defined the template for Bug tracker and didn't define for Feedback and Task.
When I view Bug tracker, the layout of description shows correctly but if I switch to Feedback ore Task, it scaled down.
![image](https://cloud.githubusercontent.com/assets/5027251/17469240/55a6131a-5d5a-11e6-9b59-91648d7d5b63.png)
![image](https://cloud.githubusercontent.com/assets/5027251/17469244/5a98d204-5d5a-11e6-8712-6c1d6d8bfe70.png)

Could you please help me?

Thanks.

**Comment by akiko-pusu** [comment] 2016-08-28 07:21
Hi, @LeGiangAnh 
Thanks for using my tiny plugin.
When you change tracker into the one which doesn’t have any templates, the body content which was filled is not removed.

Then, I could not reproduce this problem with  Miniflat2 theme (v1.2.1). 
Could you let me know the version of Miniflat2 theme you use?

**Comment by akiko-pusu** [comment] 2017-08-21 14:34
Hi, are you in the same trouble?
Since there is no reply, I’m going to close this issue. Please open new issue if you have problems.

**Closed by akiko-pusu** 2017-08-21 14:34 UTC
Labels: question, wontfix
