### ISSUE TITLE
Subject and description are cleared undesirably when the category field is changed

### ISSUE THREAD

**Issue by vividtone** [akiko-pusu/redmine_issue_templates#248] opened 2019-05-23 09:01 UTC
## Summary

Subject and description are cleared undesirably when the category field is changed. The problem is reproducible only in 0.3.2.

Although I don't have any code to fix this issue yet, our team will work on fixing this issue next  week.

Last but not least, thank you for the great plugin. My company has deployed your plugin to hundreds of Redmine instances.

## Description

You can reproduce this issue with the following steps:

1. Enable "Issue Templates" module for the project. No need to create templates
2. Open "New issue" form
3. Select a tracker which **does not** have any template
4. Fill Subject and Description fields with any text
5. Change Category field. Subject and Description are cleared

## Environment

* Redmine trunk (r18192), 4.0-stable (r18166)
* No other plugin is installed

## Workaround

Downgrading to 0.3.1 resolves this issue.

**Comment by ishikawa999** [comment] 2019-05-24 01:00
6000a3b0eb2c118a12d1c0c9fbe91169f836f751 change seems to be the cause.
When changing the category, eraseSubjectAndDescription() works to empty #issue_description and #issue_subject.

**Comment by akiko-pusu** [comment] 2019-05-24 04:05
@vividtone @ishikawa999 Thanks for supporting! 
I have another bugfix update, so that revert the commit 6000a3b soon. 
Thanks for this variable information!

**Comment by akiko-pusu** [comment] 2019-05-24 04:27
Hi, @vividtone @ishikawa999 
Now I ready for bugfix release v0.3.3.
Fortunately there are a few changesets. If you don't mind, please review this.
https://github.com/akiko-pusu/redmine_issue_templates/pull/250

And I'll include this feature with a kind of feature flag to enable / disable... >< 
Sorry for the inconvenient.

**Comment by ishikawa999** [comment] 2019-05-24 05:04
@akiko-pusu 
Thank you for your quick response.
I made a pull request, thinking how to solve this problem.
https://github.com/akiko-pusu/redmine_issue_templates/pull/251 solves the problem, so it's okay to review this pull request later.

**Comment by akiko-pusu** [comment] 2019-05-25 06:04
@ishikawa999 Thanks for your PR. 
Could you please confirm my comment? (#252)

**Comment by ishikawa999** [comment] 2019-05-25 06:34
@akiko-pusu 
Thank you for reviewing the pull request 😺 
As there are some problems as commented, I will fix it.
I will fix the problem you pointed out.

> BTW, I just invited you as a collaborator of this repository. Please feel free to create PR directly at any time you need :)
Thank you for making me a collaborator.
This is the first time to become a repository collaborator, so please let me know if I make a mistake(*´ｰ`*)

**Comment by akiko-pusu** [comment] 2019-05-26 02:55
> This is the first time to become a repository collaborator

It's my pleasure 😇 
Your PR was merged into master. Thanks for your continuous support, @vividtone and @ishikawa999 !

**Closed** 2019-05-28 02:37 UTC
